# Generated by Django 5.0 on 2024-01-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
