# Generated by Django 5.0 on 2024-01-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='slider title')),
                ('photo', models.ImageField(blank=True, upload_to='main_slider/')),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
