# Generated by Django 5.0 on 2024-01-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('status', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('twitter_link', models.URLField(default='#')),
                ('facebook_link', models.URLField()),
                ('instagram_link', models.URLField()),
                ('photo', models.ImageField(blank=True, upload_to='chefs/')),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Chefs',
            },
        ),
    ]
