# Generated by Django 5.0 on 2024-01-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_chefs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('comment', models.CharField(max_length=255)),
                ('photo', models.ImageField(default='static/images/default_avatar.jpg', upload_to='customers/')),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.AlterField(
            model_name='chefs',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='twitter_link',
            field=models.URLField(blank=True),
        ),
    ]
