# Generated by Django 5.0 on 2024-01-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customers_alter_chefs_facebook_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='progress')),
                ('value', models.FloatField()),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customers',
            name='photo',
            field=models.ImageField(upload_to='customers/'),
        ),
    ]
