# Generated by Django 5.0 on 2024-01-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_progress_alter_customers_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='title',
            field=models.CharField(max_length=100, verbose_name='progress title'),
        ),
    ]
